# Generated by Django 2.2.1 on 2019-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisossoporte',
            options={'managed': False, 'permissions': (('resumen_productos_ganancias', 'Presidente Estrategico'), ('resumen_productos_potenciales', 'Presidente Estrategico'), ('resumen_ganancias_clientes', 'Presidente Estrategico'), ('resumen_productos_vendidos', 'Presidente Estrategico'), ('resumen_tardanzas_productos', 'Presidente Estrategico'), ('semi_productos_vendidos', 'Director Tactico'), ('semi_productos_ganancias', 'Director Tactico'), ('semi_retornos_equipos', 'Director Tactico'), ('semi_productos_consigna', 'Director Tactico'), ('semi_ganancias_clientes', 'Director Tactico'), ('semi_clientes_frecuentes', 'Director Tactico'), ('etl', 'administrador'), ('gestion_usuarios', 'administrador'))},
        ),
    ]
