# Generated by Django 2.2.1 on 2019-06-14 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerencial', '0002_auto_20190612_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='permisossoporte',
            options={'managed': False, 'permissions': (('resumen_productos_ganancias', 'Presidente Estrategico'), ('resumen_productos_potenciales', 'Presidente Estrategico'), ('resumen_ganancias_clientes', 'Presidente Estrategico'), ('resumen_productos_vendidos', 'Presidente Estrategico'), ('resumen_tardanzas_productos', 'Presidente Estrategico'), ('semi_productos_vendidos', 'Director Tactico'), ('semi_productos_ganancias', 'Director Tactico'), ('semi_retornos_equipos', 'Director Tactico'), ('semi_productos_consigna', 'Director Tactico'), ('semi_ganancias_clientes', 'Director Tactico'), ('semi_clientes_frecuentes', 'Director Tactico'), ('etl', 'Administrador'), ('gestion_usuarios', 'Administrador'), ('actualizar_admin', 'Delegado'))},
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Empleado')),
            ],
        ),
    ]
