# Generated by Django 2.2.1 on 2019-06-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0004_auto_20190615_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='nombre_cliente',
        ),
        migrations.AlterField(
            model_name='compra',
            name='idProveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Proveedor'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='idCompra',
            field=models.ForeignKey(db_column='idCompra', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='idProducto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Producto'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='idProducto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idInventario',
            field=models.ForeignKey(db_column='idInventario', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Inventario'),
        ),
        migrations.AlterField(
            model_name='productoconsigna',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
        migrations.AlterField(
            model_name='productoconsigna',
            name='idProducto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Producto'),
        ),
        migrations.AlterField(
            model_name='productopotencial',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
        migrations.AlterField(
            model_name='productoretorno',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
        migrations.AlterField(
            model_name='productoretorno',
            name='idProducto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='idCliente',
            field=models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
    ]
