# Generated by Django 2.2.1 on 2019-06-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0005_auto_20190616_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fechaHora',
            new_name='fecha_hora',
        ),
    ]
