# Generated by Django 2.2.1 on 2019-06-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0006_auto_20190616_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='cantExistencias',
            new_name='cantExistencia',
        ),
    ]
