# Generated by Django 2.2.1 on 2019-06-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0007_auto_20190616_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
    ]
