# Generated by Django 2.2.1 on 2019-06-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0008_auto_20190616_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idProducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Producto')),
                ('idVenta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, to='gerencial.Venta')),
            ],
        ),
    ]
