# Generated by Django 2.2.1 on 2019-06-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0010_auto_20190619_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
    ]
