# Generated by Django 2.2.2 on 2019-06-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0011_auto_20190619_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoretorno',
            name='idProveedor',
            field=models.ForeignKey(db_column='idProveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencial.Proveedor'),
        ),
    ]
