# Generated by Django 2.2.1 on 2019-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0012_productoretorno_idproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopotencial',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
