# Generated by Django 2.2.1 on 2019-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0013_productopotencial_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoConsignaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField(db_column='idCliente')),
                ('idProducto', models.IntegerField(db_column='idProducto')),
                ('cantidad', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPotencialHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField(db_column='idCliente')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha', models.DateField(null=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoRetornoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField(db_column='idCliente')),
                ('idProducto', models.IntegerField(db_column='idProducto')),
                ('idProveedor', models.IntegerField(db_column='idProveedor')),
                ('cantidad', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
