# Generated by Django 2.2.1 on 2019-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0015_auto_20190705_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(max_length=80),
        ),
    ]
