# Generated by Django 2.2.1 on 2019-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0016_auto_20190705_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
